// apps/portfolio/frontend/src/app/shared/components/navigation/navigation.component.ts
import { Component } from '@angular/core';
import { RouterModule } from '@angular/router';
import {
  LucideAngularModule,
  Home,
  Briefcase,
  Rocket,
  Laptop,
  Github,
  Linkedin
} from 'lucide-angular';

@Component({
  selector: 'app-navigation',
  imports: [RouterModule, LucideAngularModule],
  templateUrl: './navigation.component.html'
})
export class NavigationComponent {
  public navigationItems = [
    { path: '/home', label: 'Home', icon: 'HomeIcon' },
    { path: '/experiences', label: 'Experiences', icon: 'BriefcaseIcon' },
    { path: '/projects', label: 'Projects', icon: 'RocketIcon' }
  ];

  // Lucide icons
  public readonly HomeIcon = Home;
  public readonly BriefcaseIcon = Briefcase;
  public readonly RocketIcon = Rocket;
  public readonly LaptopIcon = Laptop;
  public readonly GithubIcon = Github;
  public readonly LinkedinIcon = Linkedin;
}

<nav class="fixed top-0 left-0 right-0 z-40 bg-white dark:bg-gray-900 border-b border-gray-200 dark:border-gray-700">
  <div class="max-w-6xl mx-auto px-4 flex items-center justify-between h-16 lg:h-[70px] gap-4">
    <!-- Logo/Brand -->
    <div class="flex items-center">
      <a routerLink="/" class="flex items-center gap-2 text-gray-900 dark:text-white font-bold text-xl">
        <span class="text-2xl">👨‍💻</span>
        <span class="hidden sm:block bg-gradient-to-r from-[#667eea] to-[#764ba2] bg-clip-text text-transparent">Kenny</span>
      </a>
    </div>

    <!-- Desktop Navigation -->
    <div class="hidden lg:flex items-center gap-8">
      <a
        *ngFor="let item of navigationItems"
        [routerLink]="item.path"
        routerLinkActive="text-[#667eea] dark:text-[#667eea] font-semibold bg-gradient-to-r from-[#667eea]/10 to-[#764ba2]/10 dark:from-[#667eea]/20 dark:to-[#764ba2]/20"
        class="flex items-center gap-2 text-gray-600 dark:text-gray-300 font-medium px-4 py-2 rounded-lg transition-all duration-300 hover:text-gray-900 dark:hover:text-white hover:bg-gray-100 dark:hover:bg-gray-800"
      >
        <span class="text-lg">{{ item.icon }}</span>
        <span class="text-sm">{{ item.label }}</span>
      </a>
    </div>

    <!-- Controls -->
    <div class="flex items-center gap-4">
      <!-- Desktop Theme Toggle -->
      <div class="hidden lg:block">
        <app-theme-toggle></app-theme-toggle>
      </div>

      <!-- Mobile Theme Toggle -->
      <div class="lg:hidden">
        <app-theme-toggle></app-theme-toggle>
      </div>

      <!-- Burger Menu Button -->
      <button
        class="lg:hidden flex flex-col justify-around w-8 h-8 bg-transparent border-none cursor-pointer p-0 relative"
        (click)="toggleMenu()"
        aria-label="Toggle navigation menu"
      >
        <span class="w-full h-0.5 bg-gray-900 dark:bg-white rounded-sm transition-all duration-300 origin-center" [class]="isMenuOpen ? 'rotate-45 translate-y-1.5' : ''"></span>
        <span class="w-full h-0.5 bg-gray-900 dark:bg-white rounded-sm transition-all duration-300" [class]="isMenuOpen ? 'opacity-0' : ''"></span>
        <span class="w-full h-0.5 bg-gray-900 dark:bg-white rounded-sm transition-all duration-300 origin-center" [class]="isMenuOpen ? '-rotate-45 -translate-y-1.5' : ''"></span>
      </button>
    </div>
  </div>

  <!-- Mobile Navigation Overlay -->
  <div
    class="fixed inset-0 bg-black/50 z-40 transition-all duration-300"
    [class]="isMenuOpen ? 'opacity-100 visible' : 'opacity-0 invisible'"
    (click)="closeMenu()"
  ></div>

  <!-- Mobile Navigation Menu -->
  <div
    class="fixed top-0 right-0 w-full h-full bg-white dark:bg-gray-900 border-l border-gray-200 dark:border-gray-700 z-50 transition-all duration-300 flex flex-col shadow-2xl lg:w-80"
    [class]="isMenuOpen ? 'translate-x-0' : 'translate-x-full'"
  >
    <div class="flex items-center justify-between p-4 border-b border-gray-200 dark:border-gray-700">
      <h3 class="text-xl font-semibold text-gray-900 dark:text-white">Menu</h3>
      <button
        class="text-2xl text-gray-500 dark:text-gray-400 hover:text-gray-900 dark:hover:text-white hover:bg-gray-100 dark:hover:bg-gray-800 p-2 rounded-md transition-all duration-300"
        (click)="closeMenu()"
      >
        ×
      </button>
    </div>

    <div class="flex-1 p-4 overflow-y-auto">
      <a
        *ngFor="let item of navigationItems"
        [routerLink]="item.path"
        routerLinkActive="text-gray-900 dark:text-white bg-gradient-to-r from-[#667eea]/10 to-[#764ba2]/10 border-l-[#667eea] dark:border-l-[#667eea]"
        class="flex items-center gap-4 px-6 py-4 text-gray-600 dark:text-gray-300 font-medium transition-all duration-300 hover:text-gray-900 dark:hover:text-white hover:bg-gray-100 dark:hover:bg-gray-800 border-l-4 border-transparent"
        (click)="closeMenu()"
      >
        <span class="text-xl w-6 text-center">{{ item.icon }}</span>
        <span class="text-base">{{ item.label }}</span>
      </a>
    </div>
  </div>
</nav>

// apps/portfolio/src/shared/components/navigation.component.tsx
import { Briefcase, Github, Home, Linkedin, Rocket } from 'lucide-react';
import { NavLink } from 'react-router-dom';

import { GITHUB_URL, LINKEDIN_URL } from '@/shared/lib/social-links.constants';

const NAVIGATION_ITEMS = [
  { path: '/home', label: 'Home', icon: Home },
  { path: '/experiences', label: 'Experiences', icon: Briefcase },
  { path: '/projects', label: 'Projects', icon: Rocket }
];

const LINK_CLASS =
  'flex items-center gap-1 rounded-full px-2.5 py-1 text-xs font-medium transition-all duration-300 hover:bg-white/10 hover:text-white sm:gap-1.5 sm:px-3 sm:py-1.5 sm:text-sm';

export function Navigation() {
  return (
    <>
      <nav className="fixed bottom-4 left-0 right-0 z-40 flex justify-center px-4 sm:bottom-auto sm:top-0 sm:pt-4">
        <div className="flex h-10 items-center gap-0.5 rounded-full border border-white/10 bg-white/5 px-1.5 shadow-lg backdrop-blur-md transition-all duration-300 sm:h-12 sm:gap-1 sm:px-2">
          {NAVIGATION_ITEMS.map(item => (
            <NavLink
              key={item.path}
              to={item.path}
              className={({ isActive }) =>
                `${LINK_CLASS} ${isActive ? 'bg-white/15 text-white' : 'text-white/60'}`
              }
            >
              <item.icon className="h-3.5 w-3.5 sm:h-4 sm:w-4" />
              <span>{item.label}</span>
            </NavLink>
          ))}

          <div className="mx-1.5 h-5 w-px bg-white/15 sm:hidden"></div>

          <div className="flex items-center gap-2 sm:hidden">
            <a
              href={LINKEDIN_URL}
              target="_blank"
              rel="noopener noreferrer"
              className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-[#0077b5] text-white transition-all duration-300 hover:brightness-110"
            >
              <Linkedin size={14} />
            </a>
            <a
              href={GITHUB_URL}
              target="_blank"
              rel="noopener noreferrer"
              className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-[#333] text-white transition-all duration-300 hover:brightness-125"
            >
              <Github size={14} />
            </a>
          </div>
        </div>
      </nav>

      <div className="hidden h-16 sm:block"></div>
    </>
  );
}
