// apps/portfolio/src/shared/components/navigation.component.tsx
import { Briefcase, Github, Home, Linkedin, Rocket } from 'lucide-react';
import { NavLink } from 'react-router-dom';

import { GITHUB_URL, LINKEDIN_URL } from '@/shared/lib/social-links.constants';

const NAVIGATION_ITEMS = [
  { path: '/home', label: 'Home', icon: Home },
  { path: '/experiences', label: 'Experiences', icon: Briefcase },
  { path: '/projects', label: 'Projects', icon: Rocket }
];

const LINK_CLASS =
  'flex items-center gap-1 rounded-full px-2.5 py-1 text-xs font-medium transition-all duration-300 hover:bg-white/10 hover:text-white sm:gap-1.5 sm:px-3 sm:py-1.5 sm:text-sm';

export function Navigation() {
  return (
    <>
      <nav className="fixed bottom-4 left-0 right-0 z-40 flex justify-center px-4 sm:bottom-auto sm:top-0 sm:pt-4">
        <div className="flex h-10 items-center gap-0.5 rounded-full border border-white/10 bg-white/5 px-1.5 shadow-lg backdrop-blur-md transition-all duration-300 sm:h-12 sm:gap-1 sm:px-2">
          {NAVIGATION_ITEMS.map(item => (
            <NavLink
              key={item.path}
              to={item.path}
              className={({ isActive }) =>
                `${LINK_CLASS} ${isActive ? 'bg-white/15 text-white' : 'text-white/60'}`
              }
            >
              <item.icon className="h-3.5 w-3.5 sm:h-4 sm:w-4" />
              <span>{item.label}</span>
            </NavLink>
          ))}

          <div className="mx-1.5 h-5 w-px bg-white/15 sm:hidden"></div>

          <div className="flex items-center gap-2 sm:hidden">
            <a
              href={LINKEDIN_URL}
              target="_blank"
              rel="noopener noreferrer"
              className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-[#0077b5] text-white transition-all duration-300 hover:brightness-110"
            >
              <Linkedin size={14} />
            </a>
            <a
              href={GITHUB_URL}
              target="_blank"
              rel="noopener noreferrer"
              className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-[#333] text-white transition-all duration-300 hover:brightness-125"
            >
              <Github size={14} />
            </a>
          </div>
        </div>
      </nav>

      <div className="hidden h-16 sm:block"></div>
    </>
  );
}

// apps/portfolio/src/app/shared/components/navigation/navigation.component.ts
import { Component } from '@angular/core';
import { RouterModule } from '@angular/router';
import { LucideAngularModule, Home, Briefcase, Rocket, Github, Linkedin } from 'lucide-angular';

@Component({
  selector: 'app-navigation',
  imports: [RouterModule, LucideAngularModule],
  templateUrl: './navigation.component.html'
})
export class NavigationComponent {
  public navigationItems = [
    { path: '/home', label: 'Home', icon: Home },
    { path: '/experiences', label: 'Experiences', icon: Briefcase },
    { path: '/projects', label: 'Projects', icon: Rocket }
  ];

  public readonly GithubIcon = Github;
  public readonly LinkedinIcon = Linkedin;
}

<nav
  class="fixed bottom-4 left-0 right-0 z-40 flex justify-center px-4 sm:bottom-auto sm:top-0 sm:pt-4"
>
  <div
    class="flex h-10 items-center gap-0.5 rounded-full border border-white/10 bg-white/5 px-1.5 shadow-lg backdrop-blur-md transition-all duration-300 sm:h-12 sm:gap-1 sm:px-2"
  >
    @for (item of navigationItems; track item) {
      <a
        [routerLink]="item.path"
        routerLinkActive="text-white bg-white/15"
        class="flex items-center gap-1 rounded-full px-2.5 py-1 text-xs font-medium text-white/60 transition-all duration-300 hover:bg-white/10 hover:text-white sm:gap-1.5 sm:px-3 sm:py-1.5 sm:text-sm"
      >
        <lucide-angular [img]="item.icon" class="h-3.5 w-3.5 sm:h-4 sm:w-4"></lucide-angular>
        <span>{{ item.label }}</span>
      </a>
    }

    <div class="mx-1.5 h-5 w-px bg-white/15 sm:hidden"></div>

    <div class="flex items-center gap-2 sm:hidden">
      <a
        href="https://www.linkedin.com/in/kennytalbi"
        target="_blank"
        rel="noopener noreferrer"
        class="flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-[#0077b5] text-white transition-all duration-300 hover:brightness-110"
      >
        <lucide-angular [img]="LinkedinIcon" [size]="14"></lucide-angular>
      </a>
      <a
        href="https://github.com/kbntx"
        target="_blank"
        rel="noopener noreferrer"
        class="flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-[#333] text-white transition-all duration-300 hover:brightness-125"
      >
        <lucide-angular [img]="GithubIcon" [size]="14"></lucide-angular>
      </a>
    </div>
  </div>
</nav>

<div class="hidden h-16 sm:block"></div>
